DX improvements
HumanSignal/Adala pull request #62
Opened 2024-03-08 20:21 UTC by matt-bernstein

- switch from pdm to poetry
- improve docker setup, let docker run on local codebase instead of from github
- standardize server API structure for easier communication to LS

2024-03-08 20:22 UTC, matt-bernstein commented
@niklub LMK if you have concerns with any of these changes and I can break them out into separate PRs, if not, can you merge it?

2024-03-12 23:20 UTC, niklub requested changes

2024-03-12 23:20 UTC, niklub commented on server/README.md
> +eval "$(aws configure export-credentials --profile sandbox_dev --format env)"
`--profile <YOUR-PROFILE>`

2024-03-12 23:20 UTC, niklub commented on server/README.md
> +import json
can we pack this in `./api_codegen.sh` ?

2024-03-12 23:20 UTC, niklub commented on server/app.py
> +    status: Literal['cancelled']
Why it is not `Status.CANCELED` ?

2024-03-12 23:20 UTC, niklub commented
Overall, LGTM with a few minor changes

2024-03-13 01:31 UTC, matt-bernstein commented
thanks for the review, made the changes you suggested and will merge when this github outage is over and the PR updates :)

2024-03-13 02:33 UTC, merged