add base url for openai client
HumanSignal/Adala pull request #84
Opened 2024-04-04 13:31 UTC by hawktang

add base url for openai client to support customer url in future

2024-04-25 10:24 UTC, niklub requested changes

2024-04-25 10:24 UTC, niklub commented on adala/runtimes/_openai.py
> +            base_url=DEFAULT_CREATE_COMPLETION_URL
Does the base URL refer to the completion endpoint but not something like `https://api.openai.com/v1` ?

2024-04-26 02:04 UTC, hawktang commented
Hi Niklub,

It refer to something like https://api.openai.com/v1/

Allow to change it future can make adala support models through apps like
litellm proxy.

Peter Ze TANG (汤赜)


On Thu, Apr 25, 2024 at 6:25 PM niklub ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In adala/runtimes/_openai.py
> <https://github.com/HumanSignal/Adala/pull/84#discussion_r1579240477>:
>
> > @@ -167,7 +167,10 @@ class OpenAIChatRuntime(Runtime):
>
>      @computed_field
>      def _client(self) -> OpenAI:
> -        return OpenAI(api_key=self.openai_api_key)
> +        return OpenAI(
> +            api_key=self.openai_api_key,
> +            base_url=DEFAULT_CREATE_COMPLETION_URL
>
> Does the base URL refer to the completion endpoint but not something like
> https://api.openai.com/v1 ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HumanSignal/Adala/pull/84#pullrequestreview-2022121285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPJIZY5CS4QUF3EUBFZBVLY7DKYRAVCNFSM6AAAAABFXJK2ZSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMRSGEZDCMRYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-21 21:59 UTC, matt-bernstein commented
Hi @hawktang , thanks for the PR! Apologies for the long delay, but we've updated this change and merged it in https://github.com/HumanSignal/Adala/pull/145

2024-06-21 21:59 UTC, closed without merging